global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Gitea for basic metrics
  # (Gitea must expose /metrics endpoint - recent versions have basic metrics built-in)
  - job_name: 'gitea'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['gitea:3000']
