server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki api url

scrape_configs:
  - job_name: gitea
    static_configs:
      - targets:
          - localhost # This is the Gitea container address in Docker network
        labels:
          job: gitea-logs
          __path__: /gitea-data/gitea/log/*.log  # Correct path to Gitea logs in container

